base_url = "https://ndw.xinux.uz/"
title = "Unofficial Nix Darwin | NixOS like modules for darwin machines"
description = "NixOS like modules for darwin machines"
compile_sass = true
build_search_index = true
generate_sitemap = true
generate_robots_txt = true

theme = "juice"

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
favicon = "nix-darwin.svg"
juice_logo_name = "Unofficial Nix Darwin"
juice_logo_path = "nix-darwin.svg"
juice_extra_menu = [
  { title = "Options", link = "https://ndo.xinux.uz" },
  { title = "GitHub", link = "https://github.com/xinux-org" },
]
